//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_Detail
    {
        public int id_detail { get; set; }
        public string id { get; set; }
        public string orderId { get; set; }
        public string itemId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> unitAmount { get; set; }
    }
}
